name: Water Pump
version: "1.0.0"
slug: waterpump
description: A water pump device.
url: https://github.com/danilopeixoto/waterpump
startup: application
boot: auto
host_network: false
arch:
  - amd64
  - aarch64
services:
  - mqtt:need
options:
  broker_url: core-mosquitto
  broker_port: 1883
  broker_username: waterpump
  broker_password: default
  device_id: "1"
  device_name: Water Pump
  device_model: Diesel
  device_manufacturer: Tangerina
  controller_port_name: /dev/ttyUSB0
  controller_unit_id: 16
schema:
  broker_url: str
  broker_port: int
  broker_username: str
  broker_password: password
  device_id: str
  device_name: str
  device_model: str
  device_manufacturer: str
  controller_port_name: str
  controller_unit_id: int
