name: Water Pump
version: "1.0.0"
slug: waterpump
description: A water pump device.
url: https://github.com/danilopeixoto/waterpump
startup: application
boot: auto
host_network: false
devices:
  - /dev/gpiomem
arch:
  - amd64
  - aarch64
services:
  - mqtt:need
options:
  broker_url: core-mosquitto
  broker_port: 1883
  broker_username: waterpump
  broker_password: default
  device_id: "1"
  device_name: "Water Pump"
schema:
  broker_url: str
  broker_port: int
  broker_username: str
  broker_password: password
  device_id: str
  device_name: str
